version: "3"
services:
  app_dev:
    build:
      context: .
      dockerfile: dockerfiles/dev.Dockerfile
    image: pocket-galaxy-back-dev
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./shared:/shared
      - ./:/app
