version: "3"
services:
  app_prod:
    build:
      context: .
      dockerfile: dockerfiles/prod.Dockerfile
    image: pocket-galaxy-back-prod
    env_file:
      - .env
    volumes:
      - ./shared:/shared
    networks:
      - pocket-galaxy-back-net
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./shared:/usr/src/app/shared
      - ./misc/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT}:80"
    networks:
      - pocket-galaxy-back-net
    depends_on:
      - app_prod
networks:
  pocket-galaxy-back-net:
