# base image
FROM node:24-alpine3.21

# install apk packages
RUN apk add --no-cache git curl

# prepare workdir
RUN mkdir --parents /app
WORKDIR /app

# install npm packages
COPY package*.json ./
RUN npm install

# copy others (`src/` should be volume-bound)
COPY . .

# run
EXPOSE 5173
CMD ["npm", "run", "dev"]
