# base image
FROM python:3.12-slim

# install apt packages
RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends git curl && \
    apt-get purge --assume-yes --auto-remove && \
    rm -rf /var/lib/apt/lists/*

# set envs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBUG=1

# prepare workdir
RUN mkdir /app
WORKDIR /app

# install pip packages
COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --requirement requirements.txt

# run
EXPOSE 8000
CMD ["./scripts/entrypoint.dev.sh"]
