services:
  db:
    image: postgres:16-alpine
    env_file:
      - ${PWD}/.env.prod
    volumes:
      - ${PWD}/shared/dbfiles:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 3s
      timeout: 15s
      retries: 5
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    env_file:
      - ${PWD}/.env.prod
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${PWD}/shared/redisfiles:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 15s
      retries: 5
    restart: unless-stopped
  celery:
    image: pocket-galaxy-prod-backend
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.prod
    env_file:
      - ${PWD}/.env.prod
    command: ["celery", "--app", "project", "worker", "--loglevel=info", "--logfile=/shared/logfiles/celery.log"]
    volumes:
      - ${PWD}/shared/logfiles:/shared/logfiles
    healthcheck:
      test: ["CMD", "celery", "--app", "project", "inspect", "ping"]
      interval: 3s
      timeout: 15s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
  flower:
    image: pocket-galaxy-prod-backend
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.prod
    env_file:
      - ${PWD}/.env.prod
    command: ["celery", "--app", "project", "flower", "--uid", "celery"]
    ports:
      - 5555:5555
    volumes:
      - ${PWD}/shared/logfiles:/shared/logfiles
    depends_on:
      celery:
        condition: service_healthy
    restart: unless-stopped
  backend:
    image: pocket-galaxy-prod-backend
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile.prod
    env_file:
      - ${PWD}/.env.prod
    volumes:
      - ${PWD}/shared/staticfiles:/shared/staticfiles
      - ${PWD}/shared/mediafiles:/shared/mediafiles
      - ${PWD}/shared/logfiles:/shared/logfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 3s
      timeout: 15s
      retries: 5
    depends_on:
      celery:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    image: pocket-galaxy-prod-frontend
    build:
      context: ${PWD}/frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_SITE_TITLE: ${VITE_SITE_TITLE}
    env_file:
      - ${PWD}/.env.prod
    volumes:
      - ${PWD}/shared/logfiles:/shared/logfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 3s
      timeout: 15s
      retries: 5
    restart: unless-stopped
  nginx:
    image: nginx:1.28-alpine-slim
    env_file:
      - ${PWD}/.env.prod
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/shared/staticfiles:/shared/staticfiles
      - ${PWD}/shared/mediafiles:/shared/mediafiles
      - ${PWD}/shared/logfiles:/shared/logfiles
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: unless-stopped
