services:
  app_dev:
    build:
      context: .
      dockerfile: dockerfiles/dev.Dockerfile
    image: pocket-galaxy-front-dev
    environment:
      WEB_PORT: ${WEB_PORT}
      VITE_API_PREFIX: ${API_PREFIX}
      VITE_MEDIA_PREFIX: ${MEDIA_PREFIX}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./src:/app/src
