version: "3"
services:
  app_prod:
    build:
      context: .
      dockerfile: dockerfiles/prod.Dockerfile
      args:
        API_PREFIX: ${API_PREFIX}
        MEDIA_PREFIX: ${MEDIA_PREFIX}
    image: pocket-galaxy-front-prod
    ports:
      - "${WEB_PORT}:80"
